name: CI
on: [ push ]
jobs:
  build_and_test:
    name: Rust Cargo Build
    # We could try to cross compile like this in future:
    # https://blog.urth.org/2023/03/05/cross-compiling-rust-projects-in-github-actions/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
